import Head from 'next/head';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Bora Codar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Xablau</h1>
      </main>
    </>
  );
};

export default Home;
